In [1]:
import numpy as np
def arrayToList (array):
    array = array.reshape(1,array.size)
    l=[]
    for i in range (array.size):
        l.append(array[0,i])
    return l
              
a = np.random.randint(0,10,(2,4))
print("input: \n")
print(a)
print("output: ")
print(arrayToList(a))


input: 

[[2 2 1 6]
 [8 3 3 6]]
output: 
[2, 2, 1, 6, 8, 3, 3, 6]


In [2]:
def sumDiag (array):
    res=0
    for i in range (min(array.shape[0],array.shape[1])):
        res+=array[i,i]
    return res

a = np.random.randint(0,10,(3,3))
print("input: \n")
print(a)
print("output: ")
print(sumDiag(a))

input: 

[[9 5 1]
 [4 4 2]
 [7 0 5]]
output: 
18


In [3]:
def valuesSup (array, x):
    res=[]
    l= arrayToList(array)
    for i in l:
        if i>x:
            res.append(i)
    return res

a = np.random.randint(0,10,(3,3))
print("input: \n")
print(a)
x=int(input("give x: "))
print(valuesSup(a,x))
            

input: 

[[1 2 0]
 [9 1 5]
 [5 9 3]]
give x: 2
[9, 5, 5, 9, 3]


In [4]:
def arraySum (A,B):
    a= np.zeros((A.shape[0],A.shape[1]),dtype=int)
    for y in range(A.shape[0]):
        for x in range (B.shape[1]):
            a[y,x] = A[y,x] + B[y,x]
    return a
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))
print("A: \n")
print(a)
print("B: \n")
print(b)
print("C: \n")
print(arraySum(a,b))


A: 

[[1 5 8]
 [8 9 0]
 [6 4 7]]
B: 

[[6 6 9]
 [3 6 2]
 [3 7 9]]
C: 

[[ 7 11 17]
 [11 15  2]
 [ 9 11 16]]


In [5]:
def meanSub(array):
    res=array.copy()
    means = np.mean(a,1) ##On peut aussi calculer la moyenne par nous meme, avec une boucle for pour chaque ligne
    for y in range(array.shape[0]):
        for x in range(array.shape[1]):
            res[y,x]-=means[y]
    return res

a = np.random.rand(2,4)
print("input: \n")
print(a)
print("output: ")
print(meanSub(a))
        

input: 

[[0.62222829 0.05014267 0.16723418 0.15536635]
 [0.35955768 0.00601783 0.63824661 0.42654755]]
output: 
[[ 0.37348542 -0.1986002  -0.08150869 -0.09337653]
 [ 0.00196526 -0.35157459  0.28065419  0.06895513]]
