First of all, I inspired myself from this article to do the assignment:
https://medium.com/gft-engineering/start-to-learn-machine-learning-with-the-iris-flower-classification-challenge-4859a920e5e3

Step 1: Importing data

In [1]:
#!pip install sklearn
from sklearn.datasets import load_iris #importing the already made dataset
from sklearn.model_selection import train_test_split #importing the splitting method
from sklearn.neighbors import KNeighborsClassifier #importing the training algorithm 
#Note to Sara: before actualy going with this training algorithm, I went and checked the provided "Scikit machine learning map" in the course,
#to verify if this is an appropriate algorithm
import numpy as np 
import pandas as pd
import sklearn as sk

iris_dataset = load_iris() #Actually loading the dataset

dataframe=pd.DataFrame(iris_dataset["data"],columns=iris_dataset["feature_names"]) #displaying the data
dataframe=dataframe.assign(target=iris_dataset["target"]) #Target is the actual classification of the flower (0:setosa, 1:versicolor, 2:verginica)
print("this is our training data: ")
dataframe



this is our training data: 


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

Step 2: Splitting the data

In [2]:
#We are now splitting our data into 2 categories: train and test:
#the train category is the data we are going to use to train our model
#the test category is the data we are going to use to test the efficiency of our model; We give our model a sample from the test category and compare the results
#X is for the actual data, Y is for the result
X_train, X_test, y_train, y_test = train_test_split(iris_dataset.data, iris_dataset.target)

Step 3: Training the model

In [3]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Step 4: Testing our model

In [4]:
y_pred=knn.predict(X_test)
print(sk.metrics.confusion_matrix(y_test, y_pred))
#Elements on the diagonal of the martix are the right predictions, all the other elements are false predictions
#Our model got only 1 false prediction among 38 predictions : that's 0,97 accuracy
#(we could display this matrix in a nice way, but that would require to use the matplotlib library, which i haven't learned yet)

[[13  0  0]
 [ 0 12  1]
 [ 0  0 12]]
